### ISSUE TITLE
Multiple packages installation should happen together

### ISSUE THREAD

**Issue by mirh** [JustinTimperio/pacback#16]
Asking one at time which individual package versions you want to install is of course necessary
But installation should happen for all at once. 

First.. It's tiresome to be always confirming pacman that *yes, I'm sure*. 
Second, there's even room to break something if you are downgrading some packages that are closely connected together and some seconds/minutes pass between each one version change.

**Comment by JustinTimperio** [comment]
While I understand the frustration this is really not how pacback was meant to be used. Rolling back a long list of individual packages isn't something you should be doing constantly and defeats the automated nature of pacback. With the hook installed it's pretty much set and forget. 

I'll take a look at this though because I think it is important to avoid any version conflicts that may happen in between individual up/downgrades.

**Comment by mirh** [comment]
I see. I was also imaging a "no strings attached" mode, if I can explain. 

Still, it seems to me like installing-everything-at-once would be useful either way.

**Comment by JustinTimperio** [comment]
This is now changed.
