### ISSUE TITLE
Allow install hook to add auto-incrementing hooks

### ISSUE THREAD

**Issue by acheronfail** [JustinTimperio/pacback#22]
**Is your feature request related to a problem? Please describe.**
It would be great if the install hook auto-incremented the restore point ids, that way they don't overwrite each other when full upgrades are performed.

**Describe the solution you'd like**
After installing the `pacman` install hook, the first `pacman -Syu` should create restore point `#00`, and the next `#01`, and so on...

This would mean that we'd create a "history" of restore points correlated to full upgrades, and would be invaluable when trying to roll back full upgrades that previously occurred.

**Comment by acheronfail** [comment]
FWIW I've forked your repository and added this feature there. I'll test it out and see how it works for me for a while.

Here's the diff https://github.com/JustinTimperio/pacback/compare/master...acheronfail:feat/auto-increment-restorepoints?expand=1. It has a few changes:

* created a new `RestorePointMeta` class to assist with calculating restore points
* the `pacman` install hook now will auto-increment restore points to find an unused one

**Comment by JustinTimperio** [comment]
Hey acheronfail, Thanks for the suggestion and fork. This is something that I actually started in my dev branch. I have created a separate restore point type called snapshots, which auto-increment up to a user-defined count. This feature leaves restore points open for users store RP's as they wish, while still maintaining a catalog of each change made to the system. I got stuck working on session management though and haven't really touched it in a while. I'll definitely take a look at what you have done and see if I can integrate it into my dev branch. Wasn't honestly sure anyone was using this lol

**Comment by JustinTimperio** [comment]
Hey archeronfail,

Just wanted to give you an update here. I really like the concept you put forth. Unfortunately, I realized my Alpha code had become ![image](https://user-images.githubusercontent.com/9936997/88121207-099aea80-cb93-11ea-8b56-0ecd536559e4.png)
 
The concept, design, and features have changed so drastically, a major overhaul was in order.

----

This has inspired me to rewrite pretty much the whole thing for a proper beta release. Since I am not a huge OOP fan, I'm going with a more functional/pythonic approach using dictionaries to pass variables through my functions. This should result in a much cleaner codebase and a lot of flexibility/abstraction in the future without hurting performance. 

Not sure when I will finish this but hopefully once I'm done unraveling my own spagett, I'll get something workable merged into the master.

**Comment by JustinTimperio** [comment]
Well this has taken me way longer than I had hoped and the codebase has nearly tripled but pacback is very close to its full release. I have added a very comprehensive snapshot system that keeps a rolling list of all changes. Each snapshot only takes about 50ms to create so keeping a large archive of system changes is now achievable. 

If you would like to check out these changes, feel free to look at the dev branch. Once I'm done documenting everything for the release I will merge this into master. 

Cheers

**Comment by JustinTimperio** [comment]
After months of work its finally done! It will be a little before this makes it to pacback-git and about a week or two to work out bugs for pacback main release. 

I've also added a developer guide if you want to add any new features.

**Comment by JustinTimperio** [comment]
@acheronfail This feature is live in pacback-git!
