### ISSUE TITLE
What is the difference between Restore Point and Snapback?

### ISSUE THREAD

**Issue by juliuswz** [JustinTimperio/pacback#34]
Sorry if it is a noob question but I did not find the answer in the user guide. Thanks.

**Comment by JustinTimperio** [comment]
The developer guide has a write up on the specifics of both. I included it there because a lot of the differences are only apparent if you look at the code.

https://github.com/JustinTimperio/pacback/blob/master/DEVELOPER_GUIDE.md#restore-points

https://github.com/JustinTimperio/pacback/blob/master/DEVELOPER_GUIDE.md#snapshots

**Comment by juliuswz** [comment]
Oops, my bad, I didn't go further. So basically the snapback is like a light restore point (ignoring the differences in the code as already pointed out).

**Comment by JustinTimperio** [comment]
More or less yeah. Snapshots are created by a pacman hook whenever you make a change to your system. It keeps track of everything you do so that if you want to undo a series of changes you've made, you can just restore that snapshot. If you want to see what changes have been made system since the creation of a snapshot you just use `pacback -i ss03`. (sub the actual number you want obviously)

**Comment by juliuswz** [comment]
Got it! Thanks.
